included: 
  - Sources
  - Tests
  - Package.swift

identifier_name:
  min_length:
    warning: 0
    error: 0

disabled_rules:
  - trailing_comma # SourceKit formatter doesn't add/remove these consistently
  - no_space_in_method_call # False positive with trailing closure syntax
  - opening_brace # Disagrees with formatter
